### ISSUE TITLE
gulp build报错

### ISSUE THREAD

**Issue by taotao365s** [ustccjw/tech-blog#2]
报错了帮忙看一下:smile: 
![qq 20160107222718](https://cloud.githubusercontent.com/assets/1212932/12172765/d6961832-b58d-11e5-98d4-0cc9b778f674.png)

**Comment by ustccjw** [comment]
query-string 我也不知道为啥我 package.json 依赖写错了，神奇的是一直没报错（还没弄明白）... 刚修复了

下面的应该是 node-sass 在 windows 下问题，你可以看看 node-sass 的相关 issue。
